### ISSUE TITLE
failed to parse 'some'

### ISSUE THREAD

**Issue by unknown321** [jamespwilliams/psitop#2]
```
2023/07/24 13:29:58 failed to read cpu pressure: failed to parse 'some' /proc/pressure line "": failed to parse /proc/pressure line "": field "" didn't conform to expected key=value format

$ cat /proc/pressure/cpu 
some avg10=0.10 avg60=0.21 avg300=0.25 total=73759571709

$ uname -a
Linux debian 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
```

**Comment by jamespwilliams** [comment]
Interesting, the code assumes that `/proc/pressure/cpu` (and `io` and `memory`) always have lines for both `some` and `full`, but yours only has `some`.

I'll adapt psitop to handle the case where `full` isn't available.

**Comment by jamespwilliams** [comment]
After reading, I've realised that the `full` CPU stats are useless, because they'll always be 0 - at least one process is always running on the CPU at all time, so there's never a time in which all processes are blocked on CPU.

So I've removed CPU full metrics entirely in https://github.com/jamespwilliams/psitop/commit/c8643d0cdd8c3d05473671130fec5f2ebeccd469.
